// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVSqecuowMzq4yRKbKnzcKkANb7h7kCVQ',
    appId: '1:824081072537:web:5baa40ede84da949061308',
    messagingSenderId: '824081072537',
    projectId: 'cureheal-c3d24',
    authDomain: 'cureheal-c3d24.firebaseapp.com',
    storageBucket: 'cureheal-c3d24.appspot.com',
    measurementId: 'G-VJ57WDF504',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqw6m5zsA_8FzDBYEVuMReTqmuPMU9BaI',
    appId: '1:824081072537:android:fb436435d6874d45061308',
    messagingSenderId: '824081072537',
    projectId: 'cureheal-c3d24',
    storageBucket: 'cureheal-c3d24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZnYtLTTWxyWWVMPHZrX7oFd05dwVvkPU',
    appId: '1:824081072537:ios:c27bcc8839cfa3d8061308',
    messagingSenderId: '824081072537',
    projectId: 'cureheal-c3d24',
    storageBucket: 'cureheal-c3d24.appspot.com',
    iosBundleId: 'com.example.cureheal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZnYtLTTWxyWWVMPHZrX7oFd05dwVvkPU',
    appId: '1:824081072537:ios:c27bcc8839cfa3d8061308',
    messagingSenderId: '824081072537',
    projectId: 'cureheal-c3d24',
    storageBucket: 'cureheal-c3d24.appspot.com',
    iosBundleId: 'com.example.cureheal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVSqecuowMzq4yRKbKnzcKkANb7h7kCVQ',
    appId: '1:824081072537:web:809d1ef6d55230e0061308',
    messagingSenderId: '824081072537',
    projectId: 'cureheal-c3d24',
    authDomain: 'cureheal-c3d24.firebaseapp.com',
    storageBucket: 'cureheal-c3d24.appspot.com',
    measurementId: 'G-59XJLCCPGT',
  );

}